from typing import Protocol, TypedDict

from _camera_ui_tools.camera_ui_sdk import (
    Camera,
    CreateDownloadOptions,
    CreateStreamDownloadOptions,
    DiscoveredCamera,
    DownloadToken,
    PluginInterface,
    ProbeConfig,
    ProbeStream,
)
from _camera_ui_tools.camera_ui_sdk.internal import SensorJSON

from ..typings import PluginInfo, SensorRefreshedState


class RefreshedStates(TypedDict):
    camera: Camera
    cameraState: bool
    frameWorkerState: bool
    sensorStates: dict[str, SensorRefreshedState]


class CoreManagerInterface(Protocol):
    async def getFFmpegPath(self) -> str: ...
    async def getServerAddresses(self) -> list[str]: ...
    async def getCloudServerId(self) -> str: ...
    async def getPlugin(self, pluginName: str) -> PluginInfo | None: ...
    async def getPluginsByInterface(self, interfaceName: PluginInterface) -> list[PluginInfo]: ...


class DeviceManagerInterface(Protocol):
    async def getCamera(self, camera_name_or_id: str, plugin_id: str) -> Camera | None: ...


class CameraDeviceInterface(Protocol):
    async def refreshStates(self) -> RefreshedStates: ...
    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def snapshot(self, source_id: str, force_new: bool = False) -> bytes | None: ...
    async def probeStream(
        self, source_id: str, probe_config: ProbeConfig | None = None, refresh: bool = False
    ) -> ProbeStream | None: ...
    async def streamUrl(self, source_id: str) -> str | None: ...
    async def registerSensor(self, sensor_json: SensorJSON, plugin_id: str) -> bool: ...
    def unregisterSensor(self, sensor_id: str) -> None: ...


class DiscoveryManagerInterface(Protocol):
    async def pushDiscoveredCameras(self, plugin_id: str, cameras: list[DiscoveredCamera]) -> None: ...


class DownloadManagerInterface(Protocol):
    async def createDownload(self, options: CreateDownloadOptions) -> DownloadToken: ...
    async def createStreamDownload(self, options: CreateStreamDownloadOptions) -> DownloadToken: ...
    async def deleteDownload(self, token: str) -> None: ...
