import type { AutomationBlueprint, AutomationBlueprintInput, AutomationNode, AutomationStoreBlueprint } from '@/components/CuiAutomation/types.js';

// Secrets are regenerated by the server on import — they must never travel inside a
// shareable blueprint (neither on export nor when resolving a store/file import).
export const BLUEPRINT_SECRET_FIELDS = ['webhookSecret', 'geofenceId', 'geofenceUserSecrets'] as const;

export interface SensorBinding {
  sensorType: string;
  sensorName: string;
  sensorPluginId: string;
}

export type BindingValue = string | string[] | SensorBinding | undefined;

export interface WizardInput extends AutomationBlueprintInput {
  scan?: {
    cameraId?: string;
    pluginInterface?: string;
    sensor?: { sensorPluginId: string; sensorName: string };
    targetId?: string;
    targets?: string[];
  };
}

function nodeData(node: AutomationNode): Record<string, unknown> {
  return (node.data ?? {}) as Record<string, unknown>;
}

function humanizeInterface(iface: string): string {
  return iface.replace(/([A-Z])/g, ' $1').trim() || iface;
}

export function stripBlueprintSecrets(nodes: AutomationNode[]): AutomationNode[] {
  return nodes.map((node) => {
    const data = { ...nodeData(node) };
    for (const field of BLUEPRINT_SECRET_FIELDS) {
      delete data[field];
    }
    return { ...node, data } as unknown as AutomationNode;
  });
}

export function hasManifestInputs(blueprint: AutomationStoreBlueprint): boolean {
  return Array.isArray(blueprint.inputs) && blueprint.inputs.length > 0;
}

export function getManifestInputs(blueprint: AutomationStoreBlueprint): WizardInput[] {
  return (blueprint.inputs ?? []).map((input) => ({ ...input }));
}

export function autoScanInputs(nodes: AutomationNode[]): WizardInput[] {
  const inputs: WizardInput[] = [];

  const cameraIds: string[] = [];
  const sensorKeys: string[] = [];
  const sensors: { sensorPluginId: string; sensorName: string }[] = [];
  const pluginInterfaces: string[] = [];
  const targetIds: string[] = [];
  const targets = new Set<string>();

  for (const node of nodes) {
    const data = nodeData(node);

    const cameraId = typeof data.cameraId === 'string' ? data.cameraId : '';
    if (cameraId && !cameraIds.includes(cameraId)) {
      cameraIds.push(cameraId);
    }

    const sensorPluginId = typeof data.sensorPluginId === 'string' ? data.sensorPluginId : '';
    const sensorName = typeof data.sensorName === 'string' ? data.sensorName : '';
    if (sensorPluginId && sensorName) {
      const key = `${sensorPluginId}::${sensorName}`;
      if (!sensorKeys.includes(key)) {
        sensorKeys.push(key);
        sensors.push({ sensorPluginId, sensorName });
      }
    }

    if (node.type === 'action-plugin') {
      const pluginInterface = typeof data.pluginInterface === 'string' ? data.pluginInterface : '';
      if (pluginInterface && !pluginInterfaces.includes(pluginInterface)) {
        pluginInterfaces.push(pluginInterface);
      }
    }

    if (node.type === 'trigger-system') {
      const targetId = typeof data.targetId === 'string' ? data.targetId : '';
      if (targetId && !targetIds.includes(targetId)) {
        targetIds.push(targetId);
      }
    }

    if (Array.isArray(data.targets)) {
      for (const target of data.targets) {
        if (typeof target === 'string' && target) targets.add(target);
      }
    }
  }

  cameraIds.forEach((cameraId, index) => {
    inputs.push({ key: `camera-${index}`, type: 'camera', label: `Camera ${index + 1}`, scan: { cameraId } });
  });

  sensors.forEach((sensor, index) => {
    inputs.push({ key: `sensor-${index}`, type: 'sensor', label: sensor.sensorName || `Sensor ${index + 1}`, scan: { sensor } });
  });

  pluginInterfaces.forEach((pluginInterface) => {
    inputs.push({ key: `plugin-${pluginInterface}`, type: 'plugin', interface: pluginInterface, label: humanizeInterface(pluginInterface), scan: { pluginInterface } });
  });

  targetIds.forEach((targetId, index) => {
    inputs.push({ key: `system-target-${index}`, type: 'system-target', label: `Target ${index + 1}`, scan: { targetId } });
  });

  if (targets.size) {
    inputs.push({ key: 'notify', type: 'notification-targets', label: 'Notification targets', multiple: true, scan: { targets: [...targets] } });
  }

  return inputs;
}

export function resolveInputs(blueprint: AutomationStoreBlueprint): WizardInput[] {
  return hasManifestInputs(blueprint) ? getManifestInputs(blueprint) : autoScanInputs(blueprint.nodes);
}

export function collectRequiredInterfaces(blueprint: AutomationStoreBlueprint, inputs: WizardInput[]): string[] {
  const interfaces = new Set<string>();

  for (const input of inputs) {
    if (input.type === 'plugin' && input.interface) interfaces.add(input.interface);
  }

  for (const node of blueprint.nodes) {
    if (node.type === 'action-plugin') {
      const pluginInterface = nodeData(node).pluginInterface;
      if (typeof pluginInterface === 'string' && pluginInterface) interfaces.add(pluginInterface);
    }
  }

  return [...interfaces];
}

function inputToken(key: string): string {
  return `{{input:${key}}}`;
}

function matchInputKey(value: string): string | undefined {
  const match = /^\{\{input:(.+)\}\}$/.exec(value);
  return match ? match[1] : undefined;
}

function substituteManifest(nodes: AutomationNode[], inputs: WizardInput[], bindings: Record<string, BindingValue>): AutomationNode[] {
  const byKey = new Map(inputs.map((input) => [input.key, input]));

  // Sensor inputs fill three sibling fields, so they can't be expressed as a single scalar
  // token replacement — resolve them first, then generic-replace the remaining tokens.
  const clones = nodes.map((node) => ({ ...node, data: { ...nodeData(node) } }));

  for (const input of inputs) {
    if (input.type !== 'sensor') continue;
    const binding = bindings[input.key] as SensorBinding | undefined;
    if (!binding) continue;
    const token = inputToken(input.key);
    for (const node of clones) {
      const data = node.data;
      if (data.sensorName === token || data.sensorPluginId === token || data.sensorType === token) {
        data.sensorType = binding.sensorType;
        data.sensorName = binding.sensorName;
        data.sensorPluginId = binding.sensorPluginId;
      }
    }
  }

  const replaceValue = (value: unknown): unknown => {
    if (typeof value === 'string') {
      const key = matchInputKey(value);
      if (key === undefined) return value;
      const input = byKey.get(key);
      if (!input || input.type === 'sensor') return value;
      return bindings[key] ?? value;
    }

    if (Array.isArray(value)) {
      const result: unknown[] = [];
      for (const element of value) {
        if (typeof element === 'string') {
          const key = matchInputKey(element);
          const input = key !== undefined ? byKey.get(key) : undefined;
          if (input && input.multiple && Array.isArray(bindings[key!])) {
            result.push(...(bindings[key!] as string[]));
            continue;
          }
        }
        result.push(replaceValue(element));
      }
      return result;
    }

    if (value && typeof value === 'object') {
      const entries = Object.entries(value as Record<string, unknown>).map(([k, v]) => [k, replaceValue(v)] as const);
      return Object.fromEntries(entries);
    }

    return value;
  };

  return clones.map((node) => ({ ...node, data: replaceValue(node.data) as Record<string, unknown> }) as unknown as AutomationNode);
}

function substituteAutoScan(nodes: AutomationNode[], inputs: WizardInput[], bindings: Record<string, BindingValue>): AutomationNode[] {
  const clones = nodes.map((node) => ({ ...node, data: { ...nodeData(node) } }));

  for (const input of inputs) {
    const binding = bindings[input.key];
    if (binding === undefined) continue;

    for (const node of clones) {
      const data = node.data;

      switch (input.type) {
        case 'camera':
          if (data.cameraId === input.scan?.cameraId) data.cameraId = binding as string;
          break;
        case 'plugin':
          if (node.type === 'action-plugin' && data.pluginInterface === input.scan?.pluginInterface) data.pluginName = binding as string;
          break;
        case 'sensor':
          if (data.sensorPluginId === input.scan?.sensor?.sensorPluginId && data.sensorName === input.scan?.sensor?.sensorName) {
            const sensor = binding as SensorBinding;
            data.sensorType = sensor.sensorType;
            data.sensorName = sensor.sensorName;
            data.sensorPluginId = sensor.sensorPluginId;
          }
          break;
        case 'system-target':
          if (node.type === 'trigger-system' && data.targetId === input.scan?.targetId) data.targetId = binding as string;
          break;
        case 'notification-targets':
          if (node.type === 'action-notification') data.targets = [...(binding as string[])];
          break;
      }
    }
  }

  return clones as unknown as AutomationNode[];
}

export function resolveBlueprint(blueprint: AutomationStoreBlueprint, inputs: WizardInput[], bindings: Record<string, BindingValue>): AutomationBlueprint {
  const substituted = hasManifestInputs(blueprint) ? substituteManifest(blueprint.nodes, inputs, bindings) : substituteAutoScan(blueprint.nodes, inputs, bindings);

  return {
    version: 1,
    name: blueprint.name,
    description: blueprint.description,
    nodes: stripBlueprintSecrets(substituted),
    edges: blueprint.edges,
  };
}
